export const KPK_DISTRICTS = [
	'Abbottabad',
	'Bajaur',
	'Bannu',
	'Batagram',
	'Buner',
	'Charsadda',
	'Dera Ismail Khan',
	'Hangu',
	'Haripur',
	'Karak',
	'Khyber',
	'Kohat',
	'Kohistan Lower',
	'Kohistan Upper',
	'Kolai-Palas',
	'Kurram',
	'Lakki Marwat',
	'Malakand',
	'Mansehra',
	'Mardan',
	'Mohmand',
	'North Waziristan',
	'Nowshera',
	'Orakzai',
	'Peshawar',
	'Shangla',
	'South Waziristan Lower',
	'South Waziristan Upper',
	'Swabi',
	'Swat',
	'Tank',
	'Torghar',
	'Upper Chitral',
	'Lower Chitral',
	'Upper Dir',
	'Lower Dir'
];

export const UNKNOWN_DISTRICT = 'Unknown';
